name: Latest Image

on:
    push:
        branches:
          - main

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - name: create .env
              run: |
                touch .env
                echo "VITE_API_DOMAIN=${{ vars.VITE_API_DOMAIN }}" >> .env
                echo "VITE_LLM_DOMAIN=${{ vars.VITE_LLM_DOMAIN }}" >> .env
                echo "VITE_PARSER_DOMAIN=${{ vars.VITE_PARSER_DOMAIN }}" >> .env 

            - uses: actions/checkout@v3
            - name: Build an push an image
              run: |
                docker login --username Roaoch --password ${{ secrets.PACKAGER }} ghcr.io
                docker build . --tag ghcr.io/eternal-encoders/philosopher-frontend:latest
                docker push ghcr.io/eternal-encoders/philosopher-frontend:latest